### ISSUE TITLE
[Feedback]

### ISSUE THREAD

**Issue by Erik-E-Christensen** [canterbotto/pnw4js#2]
The documentation is very - not helpful

I would request an upgraded documentation as I do not understand how this works, I feel like it could be a great tool but the documentation doesn't help me.

**Comment by dkantereivin** [comment]
Thanks for the feedback. Where do you suggest it be improved? 

1. If you've not already done so, download and check the documentation folder which if you double click on provides a JSDoc generated documentation.
2. Send me a message on Discord @Canter#0548 and I would be able to help you out in the mean time. I'll look into improving the documentation.
Canter
